// Source: mgts-course-intelligence.md + MGTS_Fact_Verification_Tracker.xlsx
// (corrected against direct verification by Raza, June 30 2026)
// Pebble Beach Resorts® courses added per Sean's confirmed approval + IAGTO
// Program Info PDF (dated 7/23/24) — TM/R symbols mandatory on every use,
// per IAGTO agreement. Final symbol-per-name table should still be
// cross-checked against the actual signed online agreement when available.
//
// Images: all Unsplash (free commercial license, no attribution required).
// Verified live + visually reviewed 2026-07-04. Each image selected to match
// the actual character of the course (coastal, forested, links, historic, etc.)

export type Course = {
  slug: string;
  name: string;
  city: string;
  par: number;
  yards: string;
  type: string;
  hook: string;
  image?: string;
  // Golfer stats — verified from mgts-course-intelligence.md
  rating?: string;   // e.g. "75.1"
  slope?: number;    // e.g. 141
  walkable?: "walk" | "cart" | "cart-only"; // walk = encouraged, cart = recommended, cart-only = mandatory
  pace?: string;     // estimated round time e.g. "4h 30m"
  difficulty?: "championship" | "challenging" | "moderate" | "accessible";
};

export const COURSES: Course[] = [
  {
    slug: "bayonet",
    image: "/images/courses/bayonet-hero.webp",
    name: "Bayonet",
    city: "Seaside, CA",
    par: 72,
    yards: "7,094 yds",
    type: "Semi-private",
    hook: "The military-heritage championship at former Fort Ord — ranked among the toughest public courses in the country.",
    rating: "75.1",
    slope: 141,
    walkable: "cart",
    pace: "4h 45m",
    difficulty: "championship",
  },
  {
    slug: "black-horse",
    image: "/images/courses/black-horse-hero.jpg",
    name: "Black Horse",
    city: "Seaside, CA",
    par: 72,
    yards: "7,024 yds",
    type: "Semi-private",
    hook: "Sweeping vistas of Monterey Bay throughout the round, with fescue-framed fairways.",
    rating: "72.1",
    slope: 132,
    walkable: "cart",
    pace: "4h 30m",
    difficulty: "challenging",
  },
  {
    slug: "carmel-valley-ranch",
    image: "/images/courses/carmel-valley-ranch-hero.webp",
    name: "Carmel Valley Ranch",
    city: "Carmel Valley, CA",
    par: 70,
    yards: "6,117 yds",
    type: "Resort",
    hook: "Inland warmth and an early clear from the fog — a Pete Dye original with a Gene Bates redesign.",
    rating: "71.2",
    slope: 130,
    walkable: "walk",
    pace: "4h 15m",
    difficulty: "challenging",
  },
  {
    slug: "quail-lodge",
    image: "/images/courses/quail-lodge-hero.jpg",
    name: "Quail Lodge & Golf Club",
    city: "Carmel Valley, CA",
    par: 71,
    yards: "6,500 yds",
    type: "Resort / semi-private",
    hook: "A resort round in the Carmel Valley sun, away from the coastal marine layer.",
    rating: "71.4",
    slope: 128,
    walkable: "walk",
    pace: "4h 15m",
    difficulty: "moderate",
  },
  {
    slug: "laguna-seca-golf-ranch",
    image: "/images/courses/laguna-seca-hero.jpg",
    name: "Laguna Seca Golf Ranch",
    city: "Monterey, CA",
    par: 71,
    yards: "6,226 yds",
    type: "Daily-fee",
    hook: "An accessible daily-fee round close to downtown Monterey.",
    rating: "70.7",
    slope: 129,
    walkable: "cart",
    pace: "4h 15m",
    difficulty: "moderate",
  },
  {
    slug: "pacific-grove-golf-links",
    image: "https://images.unsplash.com/photo-1592919505780-303950717480?auto=format&fit=crop&w=1400&q=90",
    name: "Pacific Grove Golf Links",
    city: "Pacific Grove, CA",
    par: 70,
    yards: "5,732 yds",
    type: "Municipal",
    hook: "Ocean holes on a municipal budget — a coastal links round without the private-club price tag.",
    rating: "67.7",
    slope: 116,
    walkable: "walk",
    pace: "3h 45m",
    difficulty: "accessible",
  },
  {
    slug: "poppy-hills",
    image: "/images/courses/poppy-hills-hero.webp",
    name: "Poppy Hills Golf Course",
    city: "Pebble Beach, CA (Del Monte Forest)",
    par: 71,
    yards: "7,002 yds",
    type: "Daily-fee (NCGA)",
    hook: "Golf's most famous zip code, bentgrass greens, and no Pebble Beach Company gate fee.",
    rating: "73.5",
    slope: 135,
    walkable: "walk",
    pace: "4h 30m",
    difficulty: "challenging",
  },
  {
    slug: "club-at-pasadera",
    image: "https://images.unsplash.com/photo-1606443192517-919653213206",
    name: "The Club at Pasadera",
    city: "Monterey, CA",
    par: 71,
    yards: "6,673 yds",
    type: "Private (limited access)",
    hook: "A Jack Nicklaus Signature course on the Monterey Peninsula — Monday public access.",
    rating: "73.7",
    slope: 144,
    walkable: "cart",
    pace: "4h 30m",
    difficulty: "championship",
  },
  {
    slug: "pebble-beach-golf-links",
    name: "Pebble Beach Golf Links®",
    city: "Pebble Beach, CA",
    par: 72,
    yards: "6,828 yds",
    type: "Resort (Pebble Beach Resorts®)",
    hook: "Designed by Jack Neville and Douglas Grant, opened 1919 — the most famous cliff-top course in American golf.",
    rating: "75.5",
    slope: 145,
    walkable: "walk",
    pace: "5h 30m",
    difficulty: "championship",
  },
  {
    slug: "spyglass-hill",
    name: "Spyglass Hill Golf Course®",
    city: "Pebble Beach, CA",
    par: 72,
    yards: "6,960 yds",
    type: "Resort (Pebble Beach Resorts®)",
    hook: "A Robert Trent Jones Sr. design moving from dunes to forest — widely regarded as the toughest of the Pebble Beach Resorts® courses.",
    rating: "75.3",
    slope: 148,
    walkable: "cart",
    pace: "5h 00m",
    difficulty: "championship",
  },
  {
    slug: "links-at-spanish-bay",
    name: "The Links at Spanish Bay®",
    city: "Pebble Beach, CA",
    par: 72,
    yards: "6,726 yds",
    type: "Closed until Apr 2027",
    hook: "Closed for a full Gil Hanse-led renovation — reopening April 17, 2027.",
  },
  {
    slug: "del-monte-golf-course",
    name: "Del Monte Golf Course®",
    city: "Monterey, CA",
    par: 72,
    yards: "6,356 yds",
    type: "Resort (Pebble Beach Resorts®)",
    hook: "Originally laid out in 1897 — the oldest golf course in continuous use west of the Mississippi.",
    rating: "70.8",
    slope: 124,
    walkable: "walk",
    pace: "4h 00m",
    difficulty: "moderate",
  },
  {
    slug: "the-hay",
    name: "The Hay™",
    city: "Pebble Beach, CA",
    par: 27,
    yards: "670 yds",
    type: "Resort short course (Pebble Beach Resorts®)",
    hook: "A reimagined short course experience at Pebble Beach, originally opened 1957 and redesigned by Tiger Woods and TGR Design in 2021.",
  },
  {
    slug: "pasatiempo",
    image: "/images/courses/pasatiempo-hero.jpg",
    name: "Pasatiempo Golf Course",
    city: "Santa Cruz, CA",
    par: 70,
    yards: "6,434 yds",
    type: "Semi-private",
    hook: "Alister MacKenzie's home course, where he lived alongside the 6th green — a top-100 design in its own right.",
    rating: "73.2",
    slope: 139,
    walkable: "walk",
    pace: "4h 30m",
    difficulty: "championship",
  },
];
