// Source: mgts-lodging-intelligence.md (verified June 2 2026)
// Corrections applied per Sean's Del Monte Golf Course confirmation and
// Raza's direct verification (Casa Munras, Quail Lodge room counts).
// Drive-time matrix, room features, and dining names pulled from the same
// verified source file. Fields genuinely unverified are omitted rather
// than guessed (e.g. Quail Lodge's "best playing conditions" marketing
// claim was checked and could not be independently verified — excluded).

export type HotelDetail = {
  slug: string;
  name: string;
  city: string;
  tier: 1 | 2 | 3;
  address: string;
  phone: string;
  website: string;
  rooms: string;
  brand: string;
  hook: string;
  description: string[];
  amenities: string[];
  roomFeatures?: string[];
  diningNames?: { name: string; detail: string }[];
  uniqueDetails?: string[];
  onSiteGolf: string | null;
  airportDistance: string;
  driveTimeToCourses: { course: string; minutes: number }[];
  positioning: string;
  faqs: { q: string; a: string }[];
  gallery?: { src: string; caption: string; tag?: string }[];
};

export const HOTEL_DETAILS: Record<string, HotelDetail> = {
  "hyatt-regency-monterey": {
    slug: "hyatt-regency-monterey",
    name: "Hyatt Regency Monterey Hotel & Spa",
    city: "Monterey, CA",
    tier: 1,
    address: "1 Old Golf Course Rd, Monterey, CA 93940",
    phone: "Contact hotel directly",
    website: "hyatt.com",
    rooms: "560 guestrooms and suites",
    brand: "Hyatt Regency",
    hook: "22 secluded acres of Monterey pines, sitting directly on Del Monte™ Golf Course.",
    gallery: [
      { src: "/images/hotels/gallery/hyatt-regency-monterey-2.webp", caption: "22 secluded acres of Monterey Pines — the resort feels removed from the city despite being 2 miles from downtown.", tag: "Grounds" },
      { src: "/images/hotels/gallery/hyatt-regency-monterey-3.webp", caption: "Spa Adeline — 6 outdoor tennis courts, pools, hot tubs, and bocce courts round out the on-site recreational offering.", tag: "Spa Adeline" },
      { src: "/images/hotels/gallery/hyatt-regency-monterey-4.webp", caption: "Sea Root Restaurant & Bar — coastal Mediterranean cuisine with indoor-outdoor seating among the pines.", tag: "Sea Root Restaurant" },
      { src: "/images/hyatt-regency-monterey/gallery-2.webp", caption: "The Hyatt Regency Monterey's Monterey pine-shaded grounds — 22 acres of Pacific coast forest, 2 miles from downtown.", tag: "Grounds" },
      { src: "/images/hyatt-regency-monterey/gallery-3.webp", caption: "On-site access to Del Monte™ Golf Course — guests step directly from the hotel to the peninsula's oldest course.", tag: "Golf access" },
      { src: "/images/hyatt-regency-monterey/gallery-4.webp", caption: "The Hyatt Regency Monterey pool and recreation area — the resort anchor for a full golf trip itinerary.", tag: "Pool" },
    ],
    description: [
      "The Hyatt Regency Monterey sits on 22 secluded acres of Monterey pines, 2 miles from downtown Monterey, directly adjacent to Del Monte™ Golf Course — the oldest golf course in continuous operation west of the Mississippi, dating to 1897.",
      "With 560 guestrooms and suites, it's the largest property on this list and a natural base for group trips, offering verified stay-and-play packages with Poppy Hills, Bayonet, and Black Horse, in addition to the on-site Del Monte course.",
    ],
    amenities: [
      "2 outdoor pools + hot tubs",
      "Full-service spa (Spa Adeline)",
      "6 outdoor tennis courts",
      "Pickleball facility",
      "Bocce courts",
      "Hammock gardens",
      "24-hour fitness center",
      "Free airport shuttle",
      "EV charging",
      "Pet-friendly",
      "40,000 sq ft meeting/event space",
    ],
    diningNames: [
      { name: "Sea Root Restaurant & Bar", detail: "Coastal Mediterranean cuisine" },
      { name: "Central Coast Provisions", detail: "Casual all-day dining" },
      { name: "Beer Garden", detail: "Seasonal outdoor bar" },
    ],
    uniqueDetails: [
      "Verified stay-and-play packages with Poppy Hills, Bayonet, and Black Horse",
    ],
    onSiteGolf: "Del Monte™ Golf Course",
    airportDistance: "~8 min from MRY",
    driveTimeToCourses: [
      { course: "Bayonet / Black Horse", minutes: 8 },
      { course: "Pacific Grove Golf Links", minutes: 10 },
      { course: "The Club at Pasadera", minutes: 10 },
      { course: "Laguna Seca Golf Ranch", minutes: 12 },
      { course: "Poppy Hills", minutes: 15 },
      { course: "Quail Lodge", minutes: 20 },
      { course: "Carmel Valley Ranch", minutes: 25 },
    ],
    positioning:
      "Best base for groups wanting a central Monterey location with on-site golf and strong group rates, plus easy access to Poppy Hills, Bayonet, and Black Horse.",
    faqs: [
      {
        q: "Is the Hyatt Regency Monterey on a golf course?",
        a: "Yes. It sits directly on Del Monte™ Golf Course, the oldest golf course in continuous operation west of the Mississippi.",
      },
      {
        q: "How many rooms does the Hyatt Regency Monterey have?",
        a: "560 guestrooms and suites, making it the largest group-friendly property on the Monterey Peninsula covered here.",
      },
      {
        q: "Which other courses can I reach easily from the Hyatt Regency Monterey?",
        a: "Verified stay-and-play packages are available with Poppy Hills, Bayonet, and Black Horse, all 8–15 minutes from the property.",
      },
      {
        q: "What dining options are on-site?",
        a: "Sea Root Restaurant & Bar (Coastal Mediterranean), Central Coast Provisions for casual all-day dining, and a seasonal outdoor Beer Garden.",
      },
      {
        q: "Is the Hyatt Regency Monterey good for large groups?",
        a: "Yes — with 560 rooms and 40,000 sq ft of meeting and event space, it's built to handle large group golf trips and corporate outings.",
      },
    ],
  },
  "carmel-valley-ranch": {
    slug: "carmel-valley-ranch",
    name: "Carmel Valley Ranch",
    city: "Carmel Valley, CA",
    tier: 1,
    address: "One Old Ranch Rd, Carmel, CA 93923",
    phone: "Contact hotel directly",
    website: "carmelvalleyranch.com",
    rooms: "179 all-suites (no standard rooms)",
    brand: "The Unbound Collection by Hyatt",
    hook: "All-suite resort on 500 acres, with the only Pete Dye golf course in Northern California on-site.",
    gallery: [
      { src: "/images/hotels/gallery/carmel-valley-ranch-2.webp", caption: "All 179 accommodations are suites — minimum 800 sq ft. Gas fireplace, private deck, and valley or vineyard views in every room.", tag: "All-suite resort" },
      { src: "/images/hotels/gallery/carmel-valley-ranch-3.webp", caption: "The Pete Dye golf course on-site — his only Northern California design. Warm Carmel Valley sunshine even when the coast is fogged in.", tag: "On-site golf" },
      { src: "/images/hotels/gallery/carmel-valley-ranch-4.webp", caption: "Spa Aiyana — 10,500 sq ft of wellness space set in the Santa Lucia foothills. Nature-inspired treatments use the ranch's own gardens.", tag: "Spa Aiyana" },
      { src: "/images/hotels/gallery/carmel-valley-ranch-5.webp", caption: "Valley Kitchen — farm-to-table dining sourced from the resort's own vineyard, beehives, and organic gardens.", tag: "Valley Kitchen" },
      { src: "/images/hotels/gallery/carmel-valley-ranch-6.webp", caption: "500 acres in the Santa Lucia Mountains foothills — Carmel Valley is 15 degrees warmer than the coast on most days.", tag: "500 acres" },
      { src: "/images/carmel-valley-ranch/gallery-2.webp", caption: "Carmel Valley Ranch resort suite — all-suite accommodation on 500 acres of Carmel Valley wine country.", tag: "Suites" },
      { src: "/images/carmel-valley-ranch/gallery-3.webp", caption: "The resort grounds at Carmel Valley Ranch — vineyard, olive grove, and the warmer inland climate that defines this property.", tag: "Resort grounds" },
      { src: "/images/carmel-valley-ranch/gallery-4.webp", caption: "Carmel Valley Ranch outdoor terrace — dining and relaxation overlooking the valley floor and resort course.", tag: "Terrace" },
      { src: "/images/carmel-valley-ranch/gallery-5.webp", caption: "The pool and spa at Carmel Valley Ranch — a full resort experience anchored by the on-site Pete Dye golf course.", tag: "Pool & spa" },
    ],
    description: [
      "Carmel Valley Ranch is an all-suite resort — every accommodation is a minimum 800 sq ft (starting with the Santa Lucia Studio); there are no standard hotel rooms. Pete Dye's only Northern California golf design is on-site, and the property sits inland in the sun-drenched Santa Lucia foothills, typically 15–18°F warmer than the Monterey coast and clear of marine fog earlier in the morning. — every accommodation, from studio suites to 2-bedroom suites with up to 4 interconnected bedrooms, averages 800 square feet, with no standard rooms on property. The resort sits on 500 acres in the Carmel Valley foothills, beside the 4,400-acre Garland Ranch Regional Park.",
      "The on-site golf course is a Pete Dye original (1980), renovated by Gene Bates in 2006 — the only Pete Dye design in Northern California. The wine-country microclimate here tends to stay sunny even when the coast is fogged in.",
    ],
    amenities: [
      "On-site 18-hole Pete Dye golf course",
      "Spa Aiyana (10,500 sq ft)",
      "3 outdoor pools",
      "Tennis courts",
      "Estate vineyard, organic gardens, olive grove",
      "On-site bike trails",
      "In-suite dining",
      "Complimentary shuttle between lodging clusters",
    ],
    diningNames: [{ name: "Valley Kitchen", detail: "Farm-to-table, using the resort's own gardens and beehives" }],
    roomFeatures: [
      "Studio, 1-bedroom, and 2-bedroom suites (up to 4 interconnected bedrooms)",
      "Gas fireplace",
      "Private deck or patio",
      "Valley, vineyard, or forest views",
      "Espresso maker and refrigerator",
      "Smart room technology",
    ],
    uniqueDetails: [
      "Miniature goats at The Corral",
      "Seasonal activities: beekeeping, stargazing, axe throwing, archery, cooking classes",
    ],
    onSiteGolf: "Carmel Valley Ranch Golf Course",
    airportDistance: "~20 min from MRY",
    driveTimeToCourses: [
      { course: "Quail Lodge", minutes: 10 },
      { course: "Bernardus Lodge (The Club at Pasadera access)", minutes: 7 },
      { course: "Laguna Seca Golf Ranch", minutes: 20 },
      { course: "Poppy Hills", minutes: 20 },
      { course: "Bayonet / Black Horse", minutes: 25 },
      { course: "Pacific Grove Golf Links", minutes: 25 },
    ],
    positioning:
      "Premier all-suite golf resort, best for groups wanting a luxury resort experience with golf on-site, in a warm, sunny microclimate when the coast is foggy.",
    faqs: [
      {
        q: "Does Carmel Valley Ranch have standard hotel rooms?",
        a: "No — every accommodation on property is a suite, averaging 800 square feet, ranging from studios to multi-bedroom configurations.",
      },
      {
        q: "Who designed the golf course at Carmel Valley Ranch?",
        a: "Pete Dye designed the original course in 1980 — the only Pete Dye design in Northern California — with a 2006 renovation by Gene Bates.",
      },
      {
        q: "Is Carmel Valley Ranch usually warmer than the coast?",
        a: "Yes — its inland Carmel Valley location sits in a wine-country microclimate that often stays sunny when the coastal areas are fogged in.",
      },
      {
        q: "What's included in the suites?",
        a: "A gas fireplace, private deck or patio, valley/vineyard/forest views, an espresso maker, and a refrigerator are standard across suite types.",
      },
      {
        q: "Are there non-golf activities for the group?",
        a: "Yes — seasonal offerings include beekeeping, stargazing, axe throwing, archery, and cooking classes, plus a resident herd of miniature goats at The Corral.",
      },
    ],
  },
  "quail-lodge": {
    slug: "quail-lodge",
    name: "Quail Lodge & Golf Club",
    city: "Carmel Valley, CA",
    tier: 1,
    address: "8205 Valley Greens Dr, Carmel, CA 93923",
    phone: "(888) 828-8787",
    website: "quaillodge.com",
    rooms: "77 guest rooms + 14 suites (91 total)",
    brand: "Independent",
    hook: "Best value golf-resort combo on the peninsula, with an on-site championship course and warm Carmel Valley weather.",
    gallery: [
      { src: "/images/hotels/gallery/quail-lodge-2.webp", caption: "Lush gardens and 10 man-made lakes throughout the property — wildlife is a constant presence on the fairways.", tag: "Gardens & lakes" },
      { src: "/images/hotels/gallery/quail-lodge-3.webp", caption: "Covey Grill — on-site dining with terrace views over the Carmel Valley course.", tag: "Covey Grill" },
      { src: "/images/hotels/gallery/quail-lodge-4.webp", caption: "Robert Muir Graves original from 1964, refined by Origins Golf Design in 2015 — consistently rated best playing conditions in Central California.", tag: "On-site golf" },
      { src: "/images/quail-lodge/gallery-2.webp", caption: "Quail Lodge rooms overlooking the 10-lake golf course — stay-and-play integration at its most direct.", tag: "Rooms & course" },
      { src: "/images/quail-lodge/gallery-3.webp", caption: "The Covey Grill at Quail Lodge — post-round dining on the course with Central California wine country views.", tag: "Covey Grill" },
    ],
    description: [
      "Quail Lodge & Golf Club sits in the sunny Carmel Valley, set among lush gardens and 10 man-made lakes that draw quail, hawks, deer, turtles, and fox. The on-site golf course is a Robert Muir Graves design (1964), refined by Todd Eckenrode / Origins Golf Design in 2015.",
      "With 77 guest rooms and 14 suites (91 total keys), it's a more intimate property than the larger Tier 1 resorts, generally positioned as the best value golf-and-stay combination on the peninsula.",
    ],
    amenities: [
      "On-site 18-hole championship golf course",
      "Outdoor heated pool",
      "Tennis courts",
      "Driving range and practice green",
      "Full golf shop",
      "Golf instruction available",
    ],
    diningNames: [{ name: "Covey Grill", detail: "On-site restaurant" }],
    uniqueDetails: [
      "Wildlife on property includes quail, hawks, deer, turtles, and fox around the 10 man-made lakes",
    ],
    onSiteGolf: "Quail Lodge & Golf Club",
    airportDistance: "~15 min from MRY",
    driveTimeToCourses: [
      { course: "Carmel Valley Ranch", minutes: 10 },
      { course: "Bernardus Lodge (The Club at Pasadera access)", minutes: 15 },
      { course: "Laguna Seca Golf Ranch", minutes: 18 },
      { course: "Poppy Hills", minutes: 18 },
      { course: "Bayonet / Black Horse", minutes: 20 },
      { course: "Pacific Grove Golf Links", minutes: 22 },
    ],
    positioning:
      "Best value golf-resort combination on the peninsula, with strong course conditions and warm Carmel Valley weather — ideal for groups wanting to be on-course rather than in town.",
    faqs: [
      {
        q: "How many rooms does Quail Lodge have?",
        a: "77 guest rooms and 14 suites — 91 total keys.",
      },
      {
        q: "Who designed the Quail Lodge golf course?",
        a: "Robert Muir Graves designed the original course in 1964, with a 2015 refinement by Todd Eckenrode / Origins Golf Design.",
      },
      {
        q: "What wildlife might I see at Quail Lodge?",
        a: "The property's 10 man-made lakes and gardens draw quail, hawks, deer, turtles, and fox.",
      },
      {
        q: "Are there golf practice facilities on-site?",
        a: "Yes — a driving range, practice green, full golf shop, and golf instruction are all available on property.",
      },
      {
        q: "What's the dining like at Quail Lodge?",
        a: "Covey Grill is the on-site restaurant, serving the property's golfers and guests.",
      },
    ],
  },
  "bernardus-lodge": {
    slug: "bernardus-lodge",
    name: "Bernardus Lodge & Spa",
    city: "Carmel Valley, CA",
    tier: 1,
    address: "415 W Carmel Valley Rd, Carmel Valley, CA 93924",
    phone: "(831) 298-5389",
    website: "bernarduslodge.com",
    rooms: "73 rooms",
    brand: "Independent luxury boutique",
    hook: "A wine-country retreat with estate vineyard views and guest access to The Club at Pasadera outside of Monday.",
    gallery: [
      { src: "/images/hotels/gallery/bernardus-lodge-2.webp", caption: "Estate vineyard visible from guest rooms — Bernardus produces its own wine, served in the Marinus Restaurant.", tag: "Estate vineyard" },
      { src: "/images/hotels/gallery/bernardus-lodge-3.webp", caption: "73 rooms with stone fireplace, vaulted ceilings, private terrace, and vineyard views — no chain affiliation, fully independent.", tag: "Guest rooms" },
      { src: "/images/hotels/gallery/bernardus-lodge-4.webp", caption: "Marinus Restaurant — one of the top dining rooms on the Central Coast. Wine list focused on Carmel Valley and Santa Lucia Highlands.", tag: "Marinus Restaurant" },
      { src: "/images/bernardus-lodge/gallery-2.webp", caption: "Bernardus Lodge & Spa — wine country elegance in the heart of Carmel Valley, surrounded by the estate vineyard.", tag: "Estate vineyard" },
      { src: "/images/bernardus-lodge/gallery-3.webp", caption: "The Bernardus Lodge pool and terrace — one of the most serene settings on the Monterey Peninsula.", tag: "Pool & terrace" },
      { src: "/images/bernardus-lodge/gallery-4.webp", caption: "Bernardus Lodge room interior — luxury appointments and vineyard views in every suite.", tag: "Room interiors" },
      { src: "/images/bernardus-lodge/gallery-5.webp", caption: "The spa at Bernardus Lodge — a full-service retreat complementing the golf course access and wine country setting.", tag: "Spa" },
    ],
    description: [
      "Bernardus Lodge & Spa is a wine-country retreat in Carmel Valley, with an estate vineyard visible from many rooms and Santa Lucia mountain views throughout the property. With 73 rooms, it's the most intimate of the Tier 1 golf-anchor properties.",
      "Guests of Bernardus Lodge have access to play The Club at Pasadera — a private course generally open to the public only on Mondays — outside of the standard Monday-only window. This access arrangement should be confirmed with the property before promoting in a specific package, as terms can change.",
    ],
    amenities: [
      "Guest access to The Club at Pasadera golf course",
      "Outdoor heated pool + poolside bar",
      "Full-service spa (massages, hydrotherapy, facials, manicure/pedicure)",
      "24-hour gym",
      "Outdoor tennis courts",
      "Bocce ball, croquet, lawn games",
      "Hair salon",
      "Estate vineyard and gardens",
      "5 meeting rooms / 4,000 sq ft event space",
      "Green Key Global sustainability certification",
    ],
    diningNames: [{ name: "Lucia Restaurant & Bar", detail: "On-site, acclaimed" }],
    roomFeatures: [
      "Stone fireplace",
      "Vaulted ceilings",
      "Private terrace or balcony",
      "Vineyard views",
      "Limestone flooring",
      "Mini-fridge bar and Nespresso",
    ],
    uniqueDetails: [
      "Premier Villas (Villa Sol & Villa Carmelo): 2-bedroom/2.5-bath, 12-person dining table, private terrace with fire pits, outdoor showers",
    ],
    onSiteGolf: null,
    airportDistance: "~21 min from MRY",
    driveTimeToCourses: [
      { course: "Carmel Valley Ranch", minutes: 7 },
      { course: "Quail Lodge", minutes: 15 },
      { course: "Poppy Hills", minutes: 25 },
      { course: "Pacific Grove Golf Links", minutes: 30 },
      { course: "Bayonet / Black Horse", minutes: 30 },
    ],
    positioning:
      "Best choice for golfers wanting access to The Club at Pasadera outside of Monday, paired with a wine-country setting that's strong for groups combining golf and Carmel Valley wine tasting.",
    faqs: [
      {
        q: "Does Bernardus Lodge have an on-site golf course?",
        a: "No, but guests have access to play The Club at Pasadera, including outside its standard Monday-only public access window — confirm current terms with the property before booking.",
      },
      {
        q: "How many rooms does Bernardus Lodge have?",
        a: "73 rooms, making it the most intimate of the Tier 1 golf-anchor properties on this list.",
      },
      {
        q: "What are the Premier Villas?",
        a: "Villa Sol and Villa Carmelo are 2-bedroom, 2.5-bath villas with a 12-person dining table, a private terrace with fire pits, and outdoor showers.",
      },
      {
        q: "What's in a standard room at Bernardus Lodge?",
        a: "A stone fireplace, vaulted ceilings, a private terrace or balcony, vineyard views, and a mini-fridge bar with Nespresso.",
      },
      {
        q: "How far is Bernardus Lodge from Carmel Valley Ranch?",
        a: "About 7 minutes — the two properties are the closest golf-anchor hotels to each other in Carmel Valley.",
      },
    ],
  },
  "monterey-plaza": {
    slug: "monterey-plaza",
    name: "Monterey Plaza Hotel & Spa",
    city: "Monterey, CA",
    tier: 2,
    address: "400 Cannery Row, Monterey, CA 93940",
    phone: "(831) 646-1700",
    website: "montereyplazahotel.com",
    rooms: "285 units",
    brand: "Independent (AAA Four Diamond)",
    hook: "The only Forbes Four-Star hotel in Monterey, perched over the bay on historic Cannery Row.",
    gallery: [
      { src: "/images/hotels/gallery/monterey-plaza-2.webp", caption: "Directly on Monterey Bay — the only full-service luxury hotel with rooms directly above the water.", tag: "Waterfront" },
      { src: "/images/hotels/gallery/monterey-plaza-3.webp", caption: "Forbes Four-Star rated — the prestige property on the bay. Within walking distance of Cannery Row and the Aquarium.", tag: "Forbes Four-Star" },
      { src: "/images/hotels/gallery/monterey-plaza-4.webp", caption: "Duck Club Restaurant overlooking the bay — fresh seafood and Monterey Bay views from every table.", tag: "Duck Club Restaurant" },
      { src: "/images/hotels/gallery/monterey-plaza-5.webp", caption: "Guest rooms range from bay view to partial ocean view — many with private balconies directly above the water.", tag: "Bay view rooms" },
      { src: "/images/hotels/gallery/monterey-plaza-6.webp", caption: "8 minutes from MRY airport and 15 minutes from most peninsula golf courses — a practical central base.", tag: "Location" },
      { src: "/images/hotels/gallery/monterey-plaza-7.webp", caption: "The Spa at Monterey Plaza — treatments using Monterey Bay sea ingredients, including kelp and Pacific salt.", tag: "Spa" },
    ],
    description: [
      "Monterey Plaza Hotel & Spa is an oceanfront property perched directly over Monterey Bay on historic Cannery Row — the only Forbes Four-Star hotel in Monterey, with European-influenced architecture often described as the \"grand dame of the bay.\" With 285 units, it's a strong fit for groups wanting to be in the heart of the action, walking distance to Cannery Row and Fisherman's Wharf.",
      "There's no traditional outdoor pool here, given the waterfront setting and open bay access, but the property compensates with a rooftop-level spa and direct ocean views throughout much of the hotel. Parking is valet only.",
    ],
    amenities: [
      "Vista Blue Spa (rooftop level)",
      "Ocean-view meeting rooms",
      "Waterfront ballrooms with outdoor terraces",
      "Complimentary bicycles",
      "Valet parking only",
    ],
    uniqueDetails: [
      "Forbes Four-Star rated — one of the most decorated hotels on the peninsula.",
      "Sits directly on Cannery Row waterfront with Monterey Bay views from the majority of rooms.",
      "Walking distance to the Monterey Bay Aquarium and the main Cannery Row strip.",
    ],
    diningNames: [
      { name: "Schooners Monterey", detail: "Oceanfront dining" },
      { name: "Coastal Kitchen", detail: "Newer dining addition" },
      { name: "Tidal Coffee", detail: "Cafe" },
      { name: "Lobby Lounge", detail: "Artisan spirits and small plates" },
    ],
    onSiteGolf: null,
    airportDistance: "~10 min from MRY",
    driveTimeToCourses: [
      { course: "Pacific Grove Golf Links", minutes: 8 },
      { course: "The Club at Pasadera", minutes: 8 },
      { course: "Bayonet / Black Horse", minutes: 8 },
      { course: "Laguna Seca Golf Ranch", minutes: 12 },
      { course: "Poppy Hills", minutes: 12 },
      { course: "Quail Lodge", minutes: 20 },
      { course: "Carmel Valley Ranch", minutes: 25 },
    ],
    positioning:
      "The prestige address in Monterey for golfers wanting to be in the heart of the action — walking distance to Cannery Row, with easy drives to all peninsula courses. Strong for corporate golf groups.",
    faqs: [
      {
        q: "Is Monterey Plaza Hotel directly on the water?",
        a: "Yes, it's perched over Monterey Bay on Cannery Row — the only Forbes Four-Star hotel in Monterey.",
      },
      {
        q: "Does Monterey Plaza have a pool?",
        a: "No traditional outdoor pool — it's a waterfront property with direct bay access instead.",
      },
      {
        q: "What dining options are on-site?",
        a: "Schooners Monterey for oceanfront dining, Coastal Kitchen, Tidal Coffee cafe, and the Lobby Lounge for spirits and small plates.",
      },
      {
        q: "Is parking available at Monterey Plaza?",
        a: "Valet parking only.",
      },
      {
        q: "How close is Monterey Plaza to the golf courses?",
        a: "8 minutes to Pacific Grove Golf Links, The Club at Pasadera, and Bayonet/Black Horse — among the shortest drive times of any hotel on this site.",
      },
    ],
  },
  "intercontinental-the-clement": {
    slug: "intercontinental-the-clement",
    name: "InterContinental The Clement Monterey",
    city: "Monterey, CA",
    tier: 2,
    address: "750 Cannery Row, Monterey, CA 93940",
    phone: "(831) 375-4500",
    website: "ihg.com",
    rooms: "208 guest rooms and suites",
    brand: "InterContinental (IHG)",
    hook: "Bayfront on Cannery Row, next door to the Monterey Bay Aquarium, with panoramic coastal views.",
    gallery: [
      { src: "/images/hotels/gallery/intercontinental-the-clement-2.avif", caption: "Adjacent to the Monterey Bay Aquarium on Cannery Row — the newest bayfront hotel built in Monterey in 20+ years at its opening in 2008.", tag: "Cannery Row" },
      { src: "/images/intercontinental-the-clement-monterey/gallery-2.jpg", caption: "InterContinental The Clement Monterey — bayfront on Cannery Row with panoramic Monterey Bay views from every room.", tag: "Bay views" },
      { src: "/images/intercontinental-the-clement-monterey/gallery-3.jpg", caption: "The restaurant at InterContinental The Clement — award-winning C Restaurant looks directly over Monterey Bay.", tag: "C Restaurant" },
      { src: "/images/intercontinental-the-clement-monterey/gallery-4.jpg", caption: "InterContinental The Clement lobby and common areas — a Forbes-rated property on the most walkable stretch of Cannery Row.", tag: "Lobby" },
      { src: "/images/intercontinental-the-clement-monterey/gallery-5.jpg", caption: "Guest room at InterContinental The Clement Monterey — bay-facing rooms with floor-to-ceiling windows and direct ocean views.", tag: "Guest rooms" },
    ],
    description: [
      "InterContinental The Clement Monterey sits bayfront on Cannery Row, directly next to the Monterey Bay Aquarium, with 208 guest rooms and suites offering panoramic coastal views. Opened in 2008, it was the newest waterfront property built in Monterey in over 20 years at the time.",
      "Rooms feature Frette linens, marble bathrooms, and a mix of king or two-double configurations, with some rooms offering stone fireplaces and balconies with partial ocean views.",
    ],
    amenities: [
      "Outdoor heated pool + spa tub",
      "24-hour fitness center",
      "12 versatile meeting/event venues overlooking Monterey Bay",
      "IHG One Rewards loyalty program",
      "In-room shopping",
    ],
    diningNames: [{ name: "C Restaurant", detail: "Waterfront dining, American cuisine — whale watching from seats" }],
    roomFeatures: [
      "425–450 sq ft standard rooms",
      "King bed or two doubles",
      "Frette linens",
      "Marble bathrooms with soaking tub and separate shower",
      "Nespresso",
      "Some rooms: stone fireplace and balcony with partial ocean view",
    ],
    onSiteGolf: null,
    airportDistance: "~8 min from MRY",
    driveTimeToCourses: [
      { course: "Pacific Grove Golf Links", minutes: 8 },
      { course: "The Club at Pasadera", minutes: 8 },
      { course: "Bayonet / Black Horse", minutes: 8 },
      { course: "Laguna Seca Golf Ranch", minutes: 12 },
      { course: "Poppy Hills", minutes: 12 },
      { course: "Quail Lodge", minutes: 20 },
      { course: "Carmel Valley Ranch", minutes: 25 },
    ],
    positioning:
      "A strong alternative to Monterey Plaza for corporate or group golf, with IHG loyalty points attractive for business travelers, and a location next to the Aquarium that's ideal for groups with non-golfer partners.",
    faqs: [
      {
        q: "Is InterContinental The Clement Monterey near the Aquarium?",
        a: "Yes, it's located directly next to the Monterey Bay Aquarium on Cannery Row.",
      },
      {
        q: "How many rooms does InterContinental The Clement Monterey have?",
        a: "208 guest rooms and suites.",
      },
      {
        q: "What can I expect from the on-site restaurant?",
        a: "C Restaurant offers waterfront American dining with panoramic views — some seats even allow whale watching.",
      },
      {
        q: "Does IHG loyalty apply here?",
        a: "Yes, the property participates in the IHG One Rewards loyalty program.",
      },
      {
        q: "What are the rooms like at InterContinental The Clement Monterey?",
        a: "425–450 sq ft standard rooms with Frette linens, marble bathrooms with a soaking tub and separate shower, and a king bed or two doubles.",
      },
    ],
  },
  "portola-hotel": {
    slug: "portola-hotel",
    name: "Portola Hotel & Spa",
    city: "Monterey, CA",
    tier: 2,
    address: "Two Portola Plaza, Monterey, CA 93940",
    phone: "(888) 222-5851",
    website: "portolahotel.com",
    rooms: "379 rooms and suites",
    brand: "Independent (AAA Four Diamond)",
    hook: "The Central Coast's first LEED-certified hotel, downtown adjacent to the Monterey Conference Center.",
    gallery: [
      { src: "/images/hotels/gallery/portola-hotel-2.jpg", caption: "The Central Coast's first LEED-certified hotel — AAA Four Diamond, downtown Monterey adjacent to the Conference Center.", tag: "LEED certified" },
      { src: "/images/hotels/gallery/portola-hotel-3.jpg", caption: "379 rooms — the largest hotel in downtown Monterey, making it the best fit for large golf group room blocks.", tag: "379 rooms" },
      { src: "/images/hotels/gallery/portola-hotel-4.jpg", caption: "Jack's Restaurant & Bar on-site — casual dining in the heart of downtown Monterey, 1 mile from Cannery Row.", tag: "Jack's Restaurant" },
      { src: "/images/portola-hotel-spa/gallery-2.jpg", caption: "The Portola Hotel & Spa — the Central Coast's first LEED-certified hotel, adjacent to the Monterey Conference Center.", tag: "LEED certified" },
      { src: "/images/portola-hotel-spa/gallery-3.jpg", caption: "Portola Hotel atrium and lobby — the downtown Monterey anchor for large group trips.", tag: "Lobby" },
      { src: "/images/portola-hotel-spa/gallery-4.jpg", caption: "Guest rooms at the Portola Hotel & Spa — well-appointed rooms in the heart of downtown Monterey.", tag: "Guest rooms" },
      { src: "/images/portola-hotel-spa/gallery-5.jpg", caption: "The spa at Portola Hotel — full-service wellness to round out a golf group trip itinerary.", tag: "Spa" },
    ],
    description: [
      "Portola Hotel & Spa sits in downtown Monterey, directly adjacent to and connected with the Monterey Conference Center, one mile from Cannery Row. With 379 rooms and suites, it's the best-suited property on this list for large groups, conventions, or groups paired with a conference.",
      "The hotel was the Central Coast's first LEED-certified property, and includes a 6,000 square-foot spa — the largest day spa in Monterey County — along with an on-site craft brewery.",
    ],
    amenities: [
      "Spa on the Plaza (6,000 sq ft, 11 private treatment rooms — largest day spa in Monterey County)",
      "Craft brewery on-site",
      "60,000 sq ft meeting/event space",
      "Connected to Monterey Conference Center",
      "Outdoor heated pool",
      "Fitness center",
      "Valet + self-parking",
      "Pet-friendly",
      "Children's loyalty program",
      "No resort fee on direct bookings",
      "EV charging",
    ],
    uniqueDetails: [
      "The Central Coast's first LEED-certified hotel — a meaningful sustainability credential for environmentally conscious groups.",
      "Largest hotel in Monterey at 379 rooms, connected directly to the Monterey Conference Center — best choice for larger corporate golf groups.",
      "No resort fee on direct bookings — a real differentiator at this price point on the peninsula.",
    ],
    diningNames: [{ name: "Jacks Monterey", detail: "Breakfast and dinner, American cuisine" }],
    roomFeatures: [
      "Spanish missionary-inspired aesthetic with Monterey Bay tones",
      "Double-pane windows, ceiling fans, USB outlets",
      "King or two Queen beds",
      "Some suites with a Queen sofa sleeper",
    ],
    onSiteGolf: null,
    airportDistance: "~8 min from MRY",
    driveTimeToCourses: [
      { course: "Pacific Grove Golf Links", minutes: 10 },
      { course: "The Club at Pasadera", minutes: 10 },
      { course: "Bayonet / Black Horse", minutes: 10 },
      { course: "Laguna Seca Golf Ranch", minutes: 12 },
      { course: "Poppy Hills", minutes: 14 },
      { course: "Quail Lodge", minutes: 20 },
      { course: "Carmel Valley Ranch", minutes: 25 },
    ],
    positioning:
      "Best choice for large groups (20+ golfers), corporate outings, or groups paired with a conference, with LEED credentials appealing to sustainability-minded groups.",
    faqs: [
      {
        q: "Is Portola Hotel good for large groups?",
        a: "Yes — with 379 rooms and direct connection to the Monterey Conference Center, it's the best-suited property here for large groups, conventions, or corporate outings.",
      },
      {
        q: "Is Portola Hotel LEED-certified?",
        a: "Yes, it was the Central Coast's first LEED-certified hotel.",
      },
      {
        q: "Does Portola Hotel charge a resort fee?",
        a: "No resort fee on direct bookings, per the hotel's official policy.",
      },
      {
        q: "What's the spa like at Portola Hotel?",
        a: "Spa on the Plaza is 6,000 sq ft with 11 private treatment rooms — the largest day spa in Monterey County.",
      },
      {
        q: "What's the dining like at Portola Hotel?",
        a: "Jacks Monterey serves breakfast and dinner with an American menu, on-site at the hotel.",
      },
    ],
  },
  "casa-munras": {
    slug: "casa-munras",
    name: "Casa Munras Garden Hotel & Spa",
    city: "Monterey, CA",
    tier: 3,
    address: "700 Munras Ave, Monterey, CA 93940",
    phone: "(831) 375-2411",
    website: "hotelcasamunras.com",
    rooms: "163 rooms",
    brand: "Independent boutique",
    hook: "Monterey's first hotel, dating to 1824, with hacienda-style architecture and lush courtyard gardens.",
    gallery: [
      { src: "/images/hotels/gallery/casa-munras-2.webp", caption: "A historic Spanish-colonial property — originally the estate of Don Estéban Munras, built in 1824.", tag: "Historic 1824 estate" },
      { src: "/images/hotels/gallery/casa-munras-3.webp", caption: "Outdoor heated pool and landscaped grounds in the heart of downtown Monterey.", tag: "Pool & grounds" },
      { src: "/images/hotels/gallery/casa-munras-4.avif", caption: "Estéban Restaurant — Spanish-inspired cuisine in a garden courtyard setting, steps from downtown Monterey.", tag: "Estéban Restaurant" },
      { src: "/images/casa-munras/gallery-2.jpg", caption: "Casa Munras Garden Hotel — hacienda-style courtyards and lush gardens at Monterey's oldest hotel property.", tag: "Courtyard gardens" },
      { src: "/images/casa-munras/gallery-3.jpg", caption: "The pool at Casa Munras — a relaxed garden-hotel atmosphere close to downtown Monterey and Cannery Row.", tag: "Pool" },
      { src: "/images/casa-munras/gallery-4.jpg", caption: "Casa Munras interior rooms — the 1824 hacienda heritage preserved in the contemporary design.", tag: "Rooms" },
    ],
    description: [
      "Casa Munras Garden Hotel & Spa traces back to 1824 — Monterey's first hotel, and one of the oldest hotel properties on the Central Coast. The hacienda-style architecture and Spanish Colonial heritage are reflected throughout the downtown Monterey property, set amid picturesque courtyard gardens. It was named Best Hotel in Monterey County in 2023.",
      "With 163 rooms, it's positioned as a strong value boutique option for groups wanting authentic Monterey character without full resort pricing.",
    ],
    amenities: [
      "On-site spa",
      "Outdoor heated pool",
      "Complimentary bikes",
      "Lush courtyard gardens",
    ],
    diningNames: [{ name: "Esteban Restaurant & Bar", detail: "Spanish-California cuisine, house-made sangria" }],
    uniqueDetails: ["Named Best Hotel in Monterey County, 2023"],
    onSiteGolf: null,
    airportDistance: "~8 min from MRY",
    driveTimeToCourses: [
      { course: "Pacific Grove Golf Links", minutes: 10 },
      { course: "The Club at Pasadera", minutes: 10 },
      { course: "Bayonet / Black Horse", minutes: 8 },
      { course: "Laguna Seca Golf Ranch", minutes: 12 },
      { course: "Poppy Hills", minutes: 14 },
      { course: "Quail Lodge", minutes: 20 },
      { course: "Carmel Valley Ranch", minutes: 25 },
    ],
    positioning:
      "Best value boutique option in downtown Monterey, with historic character unique on the peninsula — strong for groups wanting authentic atmosphere without full resort pricing.",
    faqs: [
      {
        q: "How old is Casa Munras?",
        a: "It dates to 1824, making it Monterey's first hotel.",
      },
      {
        q: "How many rooms does Casa Munras have?",
        a: "163 rooms.",
      },
      {
        q: "Has Casa Munras won any recent awards?",
        a: "Yes — it was named Best Hotel in Monterey County in 2023.",
      },
      {
        q: "Are bikes available to guests?",
        a: "Yes, complimentary bikes are available for getting around downtown Monterey.",
      },
      {
        q: "What's the dining like at Casa Munras?",
        a: "Esteban Restaurant & Bar serves Spanish-California cuisine, including house-made sangria.",
      },
    ],
  },
  "hotel-abrego": {
    slug: "hotel-abrego",
    name: "Hotel Abrego",
    city: "Monterey, CA",
    tier: 3,
    address: "755 Abrego Street, Monterey, CA 93940",
    phone: "+1 (831) 372-7551",
    website: "hotelabrego.com",
    rooms: "93 rooms across four buildings",
    brand: "Independent boutique — AAA Three Diamond",
    hook: "Downtown Monterey boutique property, walkable to Cannery Row and the Monterey Bay Aquarium.",
    gallery: [
      { src: "/images/hotels/gallery/hotel-abrego-2.avif", caption: "Boutique property in downtown Monterey — close to Cannery Row, Fisherman's Wharf, and the Aquarium.", tag: "Downtown Monterey" },
      { src: "/images/hotels/gallery/hotel-abrego-3.avif", caption: "Outdoor pool and firepit lounge — a relaxed social hub after a day on the course.", tag: "Pool & firepit" },
      { src: "/images/hotels/gallery/hotel-abrego-4.avif", caption: "Guest rooms with contemporary coastal design — king or two queens, some with balcony or patio.", tag: "Guest rooms" },
      { src: "/images/hotels/gallery/hotel-abrego-5.avif", caption: "Vivolo's Chowder House on-site — Monterey-style seafood chowder and local ingredients.", tag: "Vivolo's Chowder House" },
      { src: "/images/hotels/gallery/hotel-abrego-6.avif", caption: "Fitness center and spa treatments available — practical amenities for multi-day golf groups.", tag: "Amenities" },
      { src: "/images/hotel-abrego/gallery-2.jpg", caption: "Hotel Abrego guest rooms — contemporary downtown Monterey boutique property, walkable to Cannery Row.", tag: "Guest rooms" },
      { src: "/images/hotel-abrego/gallery-3.jpg", caption: "Hotel Abrego common areas — a modern boutique experience in the heart of Monterey.", tag: "Common areas" },
      { src: "/images/hotel-abrego/gallery-4.jpg", caption: "Hotel Abrego exterior — downtown Monterey location within walking distance of the Monterey Bay Aquarium.", tag: "Exterior" },
      { src: "/images/hotel-abrego/gallery-5.jpg", caption: "The pool area at Hotel Abrego — a relaxed retreat after a day on the peninsula's courses.", tag: "Pool" },
    ],
    description: [
      "Hotel Abrego is an independent boutique property in downtown Monterey, spread across four buildings with 93 individually furnished rooms. It carries an AAA Three Diamond rating.",
      "Its downtown location puts guests within walking distance of Cannery Row (1.4 mi), the Monterey Bay Aquarium (1.6 mi), and the Path of History, making it a strong choice for groups who want to pair golf with time exploring the city rather than staying resort-bound.",
      "The property also offers private and group tour arrangements and special-interest tours, along with a full-service business center on-site for groups mixing golf with meetings.",
    ],
    amenities: [
      "Heated outdoor pool + hot tub",
      "Bistro Abrego (on-site dining, breakfast + evening dining, bar/lounge with happy hour)",
      "Fitness facilities",
      "Full-service business center on-site",
      "Banquet room for group events",
      "Group rates + private/group tours available",
      "Whale watching arrangements",
      "Aquarium ticket packages",
      "On-site parking + WiFi (bundled under a mandatory $20/night amenity fee)",
    ],
    diningNames: [
      { name: "Bistro Abrego", detail: "Daily breakfast buffet; California coastal dishes and drinks in the evening; on-site bar/lounge with happy hour" },
    ],
    uniqueDetails: [
      "AAA Three Diamond rated.",
      "Aquarium Package: 15% off standard room rates plus breakfast and a welcome drink at the bistro.",
      "Bistro Abrego Dinner Package: accommodations paired with a three-course dinner for two.",
      "Nearby attractions: Cannery Row (1.4 mi), Monterey Bay Aquarium (1.6 mi), Path of History, Monterey Sports Center, Wine Trolley Tours, Monterey County Youth Museum, California Views scenic overlook.",
    ],
    onSiteGolf: null,
    airportDistance: "~8 min from MRY (est.)",
    driveTimeToCourses: [
      { course: "Bayonet / Black Horse", minutes: 15 },
      { course: "Poppy Hills", minutes: 13 },
      { course: "Laguna Seca Golf Ranch", minutes: 12 },
      { course: "Pacific Grove Golf Links", minutes: 15 },
    ],
    positioning:
      "Best for groups who want a walkable downtown Monterey base and are planning to spend some trip time off the course — note the mandatory $20/night amenity fee when comparing total cost to other properties.",
    faqs: [
      {
        q: "Is Hotel Abrego close to the Monterey Bay Aquarium?",
        a: "Yes — it's about 1.6 miles away, an easy walk or short drive.",
      },
      {
        q: "How many rooms does Hotel Abrego have?",
        a: "93 rooms, spread across four buildings on the property.",
      },
      {
        q: "Does Hotel Abrego have a resort fee?",
        a: "Yes — a mandatory $20/night amenity fee covers parking and WiFi. Factor this into your total cost comparison.",
      },
      {
        q: "Is Hotel Abrego good for golf groups?",
        a: "It's not on a golf course, but it's centrally located with drive times of roughly 12–15 minutes to several Monterey Peninsula courses, and offers group rates.",
      },
      {
        q: "What dining is on-site at Hotel Abrego?",
        a: "Bistro Abrego serves a daily breakfast buffet and California coastal dishes in the evening, plus a bar/lounge with happy hour.",
      },
      {
        q: "What else is within walking distance of Hotel Abrego?",
        a: "Path of History, Monterey Sports Center, Wine Trolley Tours, and the Monterey County Youth Museum are all a short walk away, along with a scenic overlook known as California Views.",
      },
    ],
  },
  "embassy-suites-monterey-bay-seaside": {
    slug: "embassy-suites-monterey-bay-seaside",
    name: "Embassy Suites by Hilton Monterey Bay Seaside",
    city: "Seaside, CA",
    tier: 2,
    address: "1441 Canyon Del Rey Boulevard, Seaside, CA 93955",
    phone: "+1 (831) 393-1115",
    website: "hilton.com",
    rooms: "225 rooms, all-suite",
    brand: "Embassy Suites by Hilton — AAA Three Diamond",
    hook: "All-suite property in Seaside with a separate living room and bedroom in every unit.",
    gallery: [
      { src: "/images/hotels/gallery/embassy-suites-2.avif", caption: "All-suite hotel — every room is a two-room suite with separate living and sleeping areas, included cooked-to-order breakfast.", tag: "All-suite" },
      { src: "/images/hotels/gallery/embassy-suites-3.jpg", caption: "Indoor pool and evening manager's reception included — practical value for budget-conscious golf groups.", tag: "Indoor pool" },
      { src: "/images/hotels/gallery/embassy-suites-4.avif", caption: "Located in Seaside — directly adjacent to Bayonet & Black Horse golf courses, 10 minutes from the Monterey Peninsula courses.", tag: "Near Bayonet & Black Horse" },
      { src: "/images/embassy-suites-monterey/gallery-2.jpg", caption: "Embassy Suites by Hilton Monterey Bay — all-suite property with separate living room and bedroom in every unit.", tag: "Suite layout" },
      { src: "/images/embassy-suites-monterey/gallery-3.jpg", caption: "The atrium and lobby at Embassy Suites Monterey Bay — the daily complimentary breakfast and evening reception anchor the group value.", tag: "Atrium" },
    ],
    description: [
      "Embassy Suites by Hilton Monterey Bay Seaside is a 225-room all-suite property, carrying an AAA Three Diamond rating, with every unit featuring a separate living room and bedroom, a microwave, mini-refrigerator, wet bar, and two televisions. Select rooms offer ocean views.",
      "It's a strong choice for groups wanting extra room to spread out, with brand-standard amenities, on-site dining through lunch, dinner, and Sunday brunch, and a central Seaside location convenient to several Monterey Peninsula courses.",
      "Check-in is 4:00 PM and check-out is 11:00 AM.",
    ],
    amenities: [
      "Complimentary full cooked-to-order breakfast",
      "Indoor pool",
      "Fitness center + sauna/steam",
      "Bike trails nearby",
      "Full bar/lounge with outdoor seating and live music",
      "Sunday brunch",
      "Concierge service",
      "Gift shop",
      "Group rates + group dining available",
      "Ocean view rooms available",
      "Pet-friendly",
    ],
    roomFeatures: [
      "Separate living room and bedroom in every suite",
      "Microwave, mini-refrigerator, wet bar",
      "Two televisions",
      "Ocean view available in select rooms",
    ],
    onSiteGolf: null,
    airportDistance: "~5 min from MRY (est.)",
    driveTimeToCourses: [
      { course: "Bayonet / Black Horse", minutes: 8 },
    ],
    positioning:
      "Best for groups who want extra suite space and brand-standard reliability, centrally located in Seaside near Bayonet/Black Horse.",
    faqs: [
      {
        q: "Is Embassy Suites Monterey Bay Seaside an all-suite hotel?",
        a: "Yes — all 225 units are suites with a separate living room and bedroom.",
      },
      {
        q: "Is breakfast included at Embassy Suites Monterey Bay Seaside?",
        a: "Yes, a complimentary full cooked-to-order breakfast is included, standard for the Embassy Suites brand.",
      },
      {
        q: "How far is Embassy Suites Monterey Bay Seaside from Bayonet and Black Horse?",
        a: "About 8 minutes by car.",
      },
      {
        q: "Does Embassy Suites Monterey Bay Seaside have a pool?",
        a: "Yes, an indoor pool, along with a fitness center and sauna/steam room.",
      },
      {
        q: "Is Embassy Suites Monterey Bay Seaside pet-friendly?",
        a: "Yes.",
      },
      {
        q: "Are ocean view rooms available at Embassy Suites Monterey Bay Seaside?",
        a: "Yes, select rooms offer ocean views — request one when booking if that's a priority.",
      },
    ],
  },
  "monterey-beach-hotel": {
    slug: "monterey-beach-hotel",
    name: "Monterey Beach Hotel, A Tribute Portfolio Hotel",
    city: "Monterey, CA",
    tier: 2,
    address: "2600 Sand Dunes Drive, Monterey, CA 93940",
    phone: "+1 (831) 394-3321",
    website: "montereybeach.com",
    rooms: "188 guest rooms + 4 suites (192 total)",
    brand: "Tribute Portfolio (Marriott International) — AAA Three Diamond",
    hook: "The only Monterey Golf Tours hotel located directly on the beach.",
    gallery: [
      { src: "/images/hotels/gallery/monterey-beach-hotel-2.webp", caption: "On the beach at Monterey Bay — a rare beachfront position with direct sand access.", tag: "Beachfront" },
      { src: "/images/hotels/gallery/monterey-beach-hotel-3.webp", caption: "Pacific Ocean views from guest rooms — casual, relaxed atmosphere at an accessible price point.", tag: "Ocean views" },
      { src: "/images/monterey-beach-hotel/gallery-2.webp", caption: "Monterey Beach Hotel — the only Monterey Golf Tours property located directly on the beach.", tag: "Beachfront" },
      { src: "/images/monterey-beach-hotel/gallery-3.webp", caption: "Monterey Bay from the Monterey Beach Hotel — direct Pacific coast access steps from the rooms.", tag: "Bay views" },
      { src: "/images/monterey-beach-hotel/gallery-4.webp", caption: "The pool and terrace at Monterey Beach Hotel — beachfront relaxation after a day on the peninsula's courses.", tag: "Pool & terrace" },
    ],
    description: [
      "Monterey Beach Hotel, a Tribute Portfolio Hotel, is the only property in this collection located directly on a beach, with 188 guest rooms and 4 suites. Originally built in 1967, the property reopened under Marriott's Tribute Portfolio brand on August 21, 2024 following a complete renovation. It carries an AAA Three Diamond rating.",
      "It's a strong fit for groups who want a beachfront base with full-service amenities and meeting space, a short drive from Bayonet and Black Horse.",
      "Beyond golf, guests have easy access to whale watching, fishing, hiking and biking trails, horseback riding, sailing, scuba diving, and winery tours, making it a good fit for mixed groups where not everyone is golfing every day.",
    ],
    amenities: [
      "3 restaurants (The Lantern Room, Tidewater, Lobby Lounge) + 3 bars/lounges",
      "Outdoor pool + hot tub",
      "24-hour fitness center",
      "Beachfront, with direct beach access",
      "13 meeting rooms, 56,171 sq ft conference space",
      "Concierge services + multilingual staff (English, Spanish)",
      "Bike hire on-site",
      "Romance packages available",
      "Garden + picnic area, fireplace at reception",
      "Pet-friendly",
      "EV charging",
      "Wedding services",
    ],
    diningNames: [
      { name: "The Lantern Room", detail: "On-site restaurant" },
      { name: "Tidewater", detail: "On-site restaurant" },
      { name: "Lobby Lounge", detail: "On-site bar" },
    ],
    uniqueDetails: [
      "Built in 1967; reopened under the Tribute Portfolio brand on August 21, 2024 following a complete renovation.",
      "AAA Three Diamond rated.",
      "4.2 miles (6.7 km) from Bayonet & Black Horse Golf Course.",
      "Cooked-to-order breakfast available for a surcharge, 7–11 AM weekdays and 7 AM–1 PM weekends.",
      "Nearby activities beyond golf: whale watching, fishing, hiking/biking trails, horseback riding, sailing, scuba diving, surfing, winery tours.",
    ],
    onSiteGolf: null,
    airportDistance: "~6 min from MRY (est.)",
    driveTimeToCourses: [],
    positioning:
      "Best for groups who want a beachfront hotel with full-service amenities and meeting space, about 4.2 miles from Bayonet and Black Horse.",
    faqs: [
      {
        q: "Is Monterey Beach Hotel actually on the beach?",
        a: "Yes — it's the only Monterey Golf Tours hotel located directly on a beach, with direct beach access.",
      },
      {
        q: "How many rooms does Monterey Beach Hotel have?",
        a: "188 guest rooms plus 4 suites, for 192 total.",
      },
      {
        q: "What brand is Monterey Beach Hotel affiliated with?",
        a: "It's part of Marriott International's Tribute Portfolio, reopened August 21, 2024 following a complete renovation. It carries an AAA Three Diamond rating.",
      },
      {
        q: "How far is Monterey Beach Hotel from Bayonet and Black Horse?",
        a: "4.2 miles (6.7 km).",
      },
      {
        q: "Does Monterey Beach Hotel have meeting space for groups?",
        a: "Yes — 13 meeting rooms and 56,171 sq ft of conference space, in addition to 3 on-site restaurants and 3 bars/lounges.",
      },
      {
        q: "What can non-golfers do at Monterey Beach Hotel?",
        a: "Plenty — whale watching, fishing, hiking and biking trails, horseback riding, sailing, scuba diving, surfing, and winery tours are all accessible nearby, making it a solid pick for mixed groups.",
      },
    ],
  },

  // ─── Pebble Beach Resorts® Properties ───────────────────────────────────────
  // Source: pebblebeach.com (verified August 23 2026)
  // IAGTO agreement authorizes naming these properties with ™/® symbols.
  // No PBC logos. No pricing shown. Photographer credit required on licensed images.

  "lodge-at-pebble-beach": {
    slug: "lodge-at-pebble-beach",
    name: "The Lodge at Pebble Beach™",
    city: "Pebble Beach, CA",
    tier: 1,
    address: "1700 17-Mile Drive, Pebble Beach, CA 93953",
    phone: "866-543-9306",
    website: "pebblebeach.com/accommodations/the-lodge-at-pebble-beach",
    rooms: "Guest rooms and suites from 570 to 1,300 sq ft, including Fairway One rooms and the Palmer and Eastwood four-bedroom cottages",
    brand: "Pebble Beach Resorts®",
    hook: "Open since 1919, The Lodge at Pebble Beach™ frames the 18th green of Pebble Beach Golf Links® — golf's most recognised closing hole.",
    gallery: [
      { src: "/images/pbc-portal/lodge_2025_exterior.jpg", caption: "The Lodge at Pebble Beach™ exterior — the original 1919 property, framing the 18th green of Pebble Beach Golf Links®.\nPhoto by Jamie Alcala", tag: "Exterior" },
      { src: "/images/pbc-portal/lodge_2025_lobby.jpg", caption: "The Lodge at Pebble Beach™ lobby — classic California coastal elegance at the heart of Pebble Beach Resorts®.\nPhoto by Jamie Alcala", tag: "Lobby" },
      { src: "/images/pbc-portal/lodge-main-building_01.jpg", caption: "The Lodge at Pebble Beach™ main building — open since 1919, one of the oldest golf resort hotels in America.", tag: "Main building" },
      { src: "/images/pbc-portal/lodge_2017_interior_fairwayone_cottage.jpg", caption: "Fairway One Cottage at The Lodge at Pebble Beach™ — the Palmer and Eastwood Cottages sit directly on the first fairway, steps from the first tee.\nPhoto by Noah Webb", tag: "Fairway One Cottage" },
      { src: "/images/pbc-portal/lodge_2018_interior_oceanstudio.jpg", caption: "An Ocean Studio at The Lodge at Pebble Beach™ — rooms range from 570 to 1,300 sq ft with garden, fairway, or Pacific views.\nPhoto by Noah Webb", tag: "Ocean Studio" },
      { src: "/images/pbc-portal/fairway-one-cottage.jpg", caption: "Fairway One at The Lodge at Pebble Beach™ — 30 oversized guest rooms in three two-story buildings directly on the first fairway.\nPhoto by Noah Webb", tag: "Fairway One" },
      { src: "/images/pbc-portal/fairwayone_2017_exterior_cottage.jpg", caption: "The exterior of Fairway One Cottage at The Lodge at Pebble Beach™ — the Palmer and Eastwood Cottages each sleep four, with a shared great room and fire pit on the first fairway.\nPhoto by Noah Webb", tag: "Fairway One · Exterior" },
    ],
    description: [
      "The Lodge at Pebble Beach™ has stood at the edge of Stillwater Cove since 1919, making it the oldest property at Pebble Beach Resorts® and one of the oldest golf resort hotels in America. Guest rooms range from 570 to 1,300 square feet, with views of the landscaped gardens, the 18th fairway of Pebble Beach Golf Links®, or the Pacific Ocean beyond Carmel Bay.",
      "Fairway One, a distinctive addition to The Lodge, sits steps from the first tee of Pebble Beach Golf Links® and offers 30 oversized guest rooms across three two-story buildings, each with fairway and partial ocean views. The Palmer Cottage and Eastwood Cottage — named for two of Pebble Beach Company's most celebrated part-owners — each feature a 1,000-square-foot living room with a stacked stone fireplace, wet bar, 17-foot vaulted ceilings, and an outdoor fire pit directly on the first fairway. Four individual bedrooms feed into each shared living space, making these cottages the most sought-after accommodation for golf group buddy trips at Pebble Beach.",
      "As a Lodge guest, tee times at Pebble Beach Golf Links® and all Pebble Beach Resorts® courses can be booked up to 18 months in advance — the earliest booking window available at the resort. Access to The Beach & Tennis Club, the Spa at Pebble Beach™ (22,000 square feet, Forbes Five-Star), and a complimentary Lexus test drive are all included in the stay.",
      "The Lodge hosts 10 principal meeting rooms including the Pebble Beach Room (capacity 250) and multiple oceanfront terraces. It's the natural choice for corporate groups who want to combine world-class golf with serious meeting facilities in a single property.",
    ],
    amenities: [
      "Access to Pebble Beach Golf Links®, Spyglass Hill® Golf Course, Del Monte™ Golf Course, and The Hay™",
      "Hotel guests book tee times up to 18 months in advance (earliest window at the resort)",
      "The Spa at Pebble Beach™ — 22,000 sq ft, Forbes Five-Star, 15 massage rooms, 5 facial rooms, full salon and barber",
      "The Beach & Tennis Club — members-only club included with Lodge stay",
      "Fairway One Cottages — Palmer and Eastwood four-bedroom golf cottages on the first fairway",
      "10 meeting/event spaces — Beach Club Dining Room up to 300 reception, 200 dinner with dance floor",
      "Complimentary Lexus test drive",
      "14 dining venues across Pebble Beach Resorts® (shared)",
      "Pebble Beach Golf Academy",
      "Pet-friendly",
    ],
    roomFeatures: [
      "570–1,300 sq ft depending on room type",
      "Garden, fairway, or Stillwater Cove ocean views",
      "300-thread count Egyptian cotton sheets",
      "Premium fully stocked honor bar",
      "Complimentary non-alcoholic beverages and snacks",
      "In-room safe, coffee maker",
      "The Spa Collection bath amenities — shampoo, conditioner, body wash, lotion",
      "Two microfibre robes and slippers",
      "Fairway One Cottages: 1,000 sq ft living room, stacked stone fireplace, wet bar, outdoor fire pit",
    ],
    uniqueDetails: [
      "Frames the 18th green of Pebble Beach Golf Links® — golf's most photographed closing hole",
      "Open since 1919 — the original property at Pebble Beach Resorts®",
      "Palmer and Eastwood Cottages on the first fairway — named for Clint Eastwood and Arnold Palmer, Pebble Beach Company part-owners",
      "Forbes Five-Star Spa on-site",
      "2027 U.S. Open Championship host venue",
    ],
    diningNames: [
      { name: "Stillwater Bar & Grill", detail: "Oceanfront dining on Carmel Bay — seafood and California cuisine" },
      { name: "Tap Room", detail: "Casual bar and grill with views of the 18th hole" },
      { name: "Club XIX", detail: "Fine dining overlooking Stillwater Cove — jacket preferred" },
    ],
    onSiteGolf: "Pebble Beach Golf Links®",
    airportDistance: "~15 min from MRY (Monterey Regional Airport)",
    driveTimeToCourses: [
      { course: "Pebble Beach Golf Links®", minutes: 0 },
      { course: "Spyglass Hill® Golf Course", minutes: 5 },
      { course: "Del Monte™ Golf Course", minutes: 10 },
      { course: "Poppy Hills Golf Course", minutes: 8 },
      { course: "Bayonet", minutes: 20 },
      { course: "Black Horse", minutes: 20 },
      { course: "Pacific Grove Golf Links", minutes: 10 },
    ],
    positioning: "The original Pebble Beach property. Best for groups where the Pebble Beach Golf Links® experience is the primary reason for the trip — Fairway One Cottages are the definitive buddy-trip accommodation. Corporate groups benefit from the 10-room meeting facility and the 300-person Beach Club.",
    faqs: [
      {
        q: "How far in advance can Lodge guests book Pebble Beach tee times?",
        a: "Guests of The Lodge at Pebble Beach™ can book tee times up to 18 months in advance — the longest advance booking window at Pebble Beach Resorts®. This is the single most important practical advantage of staying on-property for serious golf groups.",
      },
      {
        q: "What are the Fairway One Cottages?",
        a: "The Palmer and Eastwood Cottages sit directly on the first fairway of Pebble Beach Golf Links®. Each cottage has four individual bedrooms sharing a 1,000-square-foot living room with a stacked stone fireplace, wet bar, and an outdoor terrace with a fire pit overlooking the fairway. Named for Clint Eastwood and Arnold Palmer, two of Pebble Beach Company's most celebrated part-owners. These are the best accommodation in the world for a four-couple golf buddy trip.",
      },
      {
        q: "Is The Lodge suitable for corporate golf events?",
        a: "Yes — The Lodge has 10 principal meeting rooms including the Beach Club Dining Room, which accommodates up to 300 for a reception or 200 for a seated dinner with dance floor. The Pebble Beach Room seats up to 250. Combined with access to all five Pebble Beach Resorts® golf courses, it's the complete corporate golf event venue.",
      },
      {
        q: "Is there a minimum stay requirement to play Pebble Beach Golf Links®?",
        a: "Yes — Pebble Beach Resorts® requires a minimum stay to play Pebble Beach Golf Links®, particularly for multiple rounds. We handle all booking through our IAGTO partnership — get a custom quote and we'll confirm the current requirements for your dates.",
      },
      {
        q: "What is the dress code on the golf courses?",
        a: "Collared shirts with slacks or walking shorts. No blue jeans or denim. Soft spikes recommended but not required. Multi-stud rubber-soled shoes are not recommended.",
      },
    ],
  },

  "inn-at-spanish-bay": {
    slug: "inn-at-spanish-bay",
    name: "The Inn at Spanish Bay™",
    city: "Pebble Beach, CA",
    tier: 1,
    address: "2700 17-Mile Drive, Pebble Beach, CA 93953",
    phone: "866-543-9306",
    website: "pebblebeach.com/accommodations/the-inn-at-spanish-bay",
    rooms: "Guest rooms and suites from 470 to 2,100 sq ft, all with gas fireplace and most with private patio or balcony",
    brand: "Pebble Beach Resorts®",
    hook: "Tucked between Del Monte Forest and the Pacific Ocean — the most romantic and most dramatic of the three Pebble Beach Resorts® properties.",
    gallery: [
      { src: "/images/pbc-portal/inn_2020_interior_lobby.jpg", caption: "The lobby at The Inn at Spanish Bay™ — a 270-room resort overlooking the Pacific and the Links at Spanish Bay® golf course.\nPhoto by Sherman Chu", tag: "Lobby" },
      { src: "/images/pbc-portal/the-inn-ocean-view-room.jpg", caption: "An ocean view room at The Inn at Spanish Bay™ — every room features a gas fireplace and private patio or balcony with forest, fairway, or Pacific views.\nPhoto by Noah Webb", tag: "Ocean view room" },
      { src: "/images/pbc-portal/the-inn-presidential-suite.jpg", caption: "The Presidential Suite at The Inn at Spanish Bay™ — 2,100 sq ft of oceanfront luxury at Pebble Beach Resorts®.", tag: "Presidential Suite" },
      { src: "/images/pbc-portal/the-inn-at-spanish-bay---fire-pits.jpg", caption: "The fire pits at The Inn at Spanish Bay™ — each evening a bagpiper plays on the 18th green as the sun sets over the Pacific.\nPhoto by Joann Dost", tag: "Fire pits" },
      { src: "/images/pbc-portal/inn_2018_executiveforestsuite.jpg", caption: "The Executive Forest Suite at The Inn at Spanish Bay™ — the forest-facing room category with views into the Del Monte Forest pines.\nPhoto by Sherman Chu", tag: "Executive Forest Suite" },
      { src: "/images/pbc-portal/the-inn-spanish-bay-suite.jpg", caption: "The Spanish Bay Suite at The Inn at Spanish Bay™ — one of the premier oceanfront suite categories with panoramic Pacific views.\nPhoto by Sherman Chu", tag: "Spanish Bay Suite" },
      { src: "/images/pbc-portal/the-inn-spanish-bay-suite-1.jpg", caption: "The Spanish Bay Suite at The Inn at Spanish Bay™ — spacious interiors with the signature coastal California design palette.\nPhoto by Sherman Chu", tag: "Spanish Bay Suite" },
      { src: "/images/pbc-portal/the-inn-at-spanish-bay-guest-rooms.jpg", caption: "Guest rooms at The Inn at Spanish Bay™ — all rooms feature gas fireplaces and most have private patios or balconies.", tag: "Guest rooms" },
      { src: "/images/pbc-portal/spanish-bay-bagpiper.jpg", caption: "The Spanish Bay bagpiper at The Inn at Spanish Bay™ — a Scottish piper plays every evening at sunset from the first tee to the fire pits.\nPhoto by Sherman Chu", tag: "Bagpiper · Sunset" },
    ],
    description: [
      "The Inn at Spanish Bay™ sits at the northern end of the 17-Mile Drive, where the Del Monte Forest meets the Pacific coastline. Every guest room features a gas-burning fireplace and, in most cases, a private patio or balcony overlooking the forest, fairways, or open ocean. Rooms range from 470 to 2,100 square feet — the Grand Suite offers a dining/conference table for 10 and a grand piano.",
      "The Inn overlooks The Links at Spanish Bay®, currently closed for a full Gil Hanse redesign and scheduled to reopen April 17, 2027. When it reopens, guests of The Inn will have the most direct access to play the redesigned course — the only true links-style course at Pebble Beach Resorts®, designed with ocean-exposed dunes, firm fast fairways, and views across the Pacific on every hole.",
      "The bagpiper is The Inn's defining evening ritual: a lone Scottish piper begins at the first tee in front of STICKS restaurant and plays for 45 minutes, finishing at the Spanish Bay fire pits beside the second green at sunset. It happens every day, rain or shine.",
      "With more than 14,000 square feet of flexible meeting space, The Inn's Grand Ballroom accommodates up to 800 guests — the largest event capacity at Pebble Beach Resorts®. The Peppoli Lawn overlooks the Pacific Coast and is one of the most dramatic outdoor event settings in California.",
    ],
    amenities: [
      "Access to all Pebble Beach Resorts® golf courses — The Links at Spanish Bay® reopens April 17, 2027",
      "Hotel guests book tee times up to 18 months in advance",
      "13,343 sq ft of meeting space — Grand Ballroom up to 800 guests",
      "Spanish Bay Club & Tennis Pavilion (private club, Inn guests have access)",
      "Stave Wine Cellar — wine lounge and shop on-site",
      "Seaside boardwalk with hidden coves and sandy beaches",
      "The Spa at Pebble Beach™ — shared with The Lodge (15 min courtesy shuttle)",
      "The Beach & Tennis Club — accessible via courtesy shuttle",
      "Multiple on-site restaurants and a fire pit lounge",
      "Scottish bagpiper at sunset — daily tradition, rain or shine",
    ],
    roomFeatures: [
      "470–2,100 sq ft depending on room type",
      "Gas-burning fireplace in every room",
      "Private patio or balcony (most rooms) — forest, fairway, or Pacific Ocean views",
      "Flat-screen TV with cable",
      "Complimentary Wi-Fi",
      "300-thread count Egyptian cotton sheets",
      "Premium fully stocked honor bar",
      "The Spa Collection bath amenities",
      "Two microfibre robes and slippers",
      "Grand Suite: 2,100 sq ft, dining table seats 10, grand piano, conference capabilities",
    ],
    uniqueDetails: [
      "The bagpiper plays every evening at sunset — from the 1st tee to the Spanish Bay fire pits",
      "Overlooks The Links at Spanish Bay® — the only links-style course at Pebble Beach Resorts®, reopening April 17, 2027 after Gil Hanse redesign",
      "Largest event venue at Pebble Beach Resorts® — Grand Ballroom up to 800 guests",
      "The most dramatic ocean-and-dunes setting of the three Pebble Beach Resorts® properties",
      "Stave Wine Cellar — a Monterey wine experience on-site",
    ],
    diningNames: [
      { name: "STICKS", detail: "Casual all-day dining on the links — views of the 1st fairway of The Links at Spanish Bay®" },
      { name: "Peppoli", detail: "Tuscan-inspired fine dining — fireplace and forest terrace" },
      { name: "Stave Wine Cellar", detail: "Wine lounge and shop — Monterey-focused selections" },
    ],
    onSiteGolf: "The Links at Spanish Bay® (closed — reopens April 17, 2027)",
    airportDistance: "~15 min from MRY (Monterey Regional Airport)",
    driveTimeToCourses: [
      { course: "Pebble Beach Golf Links®", minutes: 10 },
      { course: "Spyglass Hill® Golf Course", minutes: 8 },
      { course: "Del Monte™ Golf Course", minutes: 15 },
      { course: "Poppy Hills Golf Course", minutes: 12 },
      { course: "Pacific Grove Golf Links", minutes: 5 },
      { course: "Bayonet", minutes: 18 },
      { course: "Black Horse", minutes: 18 },
    ],
    positioning: "Best for golfers who want the links experience at Spanish Bay® when it reopens in 2027, or for groups who want the most dramatic coastal setting with large-event capability. The Grand Ballroom (800 guests) makes it the top choice for large corporate golf events at Pebble Beach Resorts®.",
    faqs: [
      {
        q: "When does The Links at Spanish Bay® reopen?",
        a: "The Links at Spanish Bay® is scheduled to reopen April 17, 2027, following a full redesign by Gil Hanse. Guests of The Inn at Spanish Bay™ will have direct access to the redesigned course. We're taking group waitlist requests now — get in touch to secure early tee times.",
      },
      {
        q: "What is the bagpiper tradition at The Inn?",
        a: "A lone Scottish bagpiper begins at the first tee of The Links at Spanish Bay® in front of STICKS restaurant every evening and plays for approximately 45 minutes, finishing at the Spanish Bay fire pits by the second green as the sun sets over the Pacific. It happens every day of the year, rain or shine — and is one of the most memorable moments of a Pebble Beach stay.",
      },
      {
        q: "Can The Inn host our corporate golf event?",
        a: "Yes — The Inn has over 14,000 square feet of meeting space, with the Grand Ballroom accommodating up to 800 guests. The Peppoli Lawn provides a panoramic outdoor space overlooking the Pacific coast. Combined with access to all five Pebble Beach Resorts® golf courses, it's well-suited for large-scale corporate events. We handle the full coordination.",
      },
      {
        q: "How does The Inn differ from The Lodge?",
        a: "The Lodge frames the 18th green of Pebble Beach Golf Links® and is the historic heart of the resort. The Inn is the more modern property, set in the dunes and forest at the northern end of the 17-Mile Drive with an entirely different character — more intimate, more coastal, with the links course directly outside and the bagpiper each evening. Both offer the same 18-month tee time booking advantage.",
      },
    ],
  },

  "casa-palmero": {
    slug: "casa-palmero",
    name: "Casa Palmero™",
    city: "Pebble Beach, CA",
    tier: 1,
    address: "1518 Cypress Drive, Pebble Beach, CA 93953",
    phone: "866-543-9306",
    website: "pebblebeach.com/accommodations/casa-palmero-at-pebble-beach",
    rooms: "24 private rooms and suites, 585–1,268 sq ft, all starting with a private garden patio or views of the 1st or 2nd fairway of Pebble Beach Golf Links®",
    brand: "Pebble Beach Resorts®",
    hook: "The most intimate property at Pebble Beach Resorts® — just 24 rooms, a personal concierge, and the entire estate available for exclusive group buyout.",
    description: [
      "Casa Palmero™ is a Mediterranean-style estate tucked along the 1st and 2nd fairways of Pebble Beach Golf Links®, adjacent to The Spa at Pebble Beach™. With just 24 rooms and suites, it operates at a scale of personal service that the larger Lodge and Inn cannot replicate — fresh flowers delivered daily, complimentary cocktails each evening, morning yoga in the courtyard, and a personal concierge who handles every aspect of the stay.",
      "Rooms start at 585 square feet and are appointed with open wood-beamed ceilings, gas fireplaces, and oversized soaking tubs. Ground-floor Spa rooms open directly onto private garden patios, each with an outdoor whirlpool spa. The Palmero Suite reaches 1,500 square feet and opens onto the estate's central courtyard.",
      "Casa Palmero can be reserved exclusively by a single group in advance — all 24 rooms, the main house with its living room, library and billiard room, the bar and lounge, and the heated pool. For corporate groups, incentive trips, or high-net-worth buddy trips where privacy is the priority, this is the only property in golf that offers this combination of location, intimacy, and complete exclusivity.",
      "Guests have access to all five Pebble Beach Resorts® golf courses and may book tee times up to 12 months in advance. The Forbes Five-Star Spa at Pebble Beach™ is steps away.",
    ],
    amenities: [
      "Full exclusive buyout available — all 24 rooms reserved by one group",
      "Access to all Pebble Beach Resorts® golf courses",
      "Tee times bookable up to 12 months in advance",
      "Personal concierge — handles every aspect of the stay",
      "Daily fresh flowers in all rooms",
      "Complimentary cocktails each evening",
      "Morning yoga in the courtyard",
      "Heated outdoor pool with refreshment from The Spa Juice Bar",
      "The Spa at Pebble Beach™ — steps away (Forbes Five-Star)",
      "24-hour room service with healthful menu",
      "Boardroom — 1,050 sq ft, up to 30 guests",
      "Smaller conference room — up to 16 guests",
      "Outdoor patio — 711 sq ft, up to 48 guests for private catered events",
      "Situated along 1st and 2nd fairways of Pebble Beach Golf Links®",
    ],
    roomFeatures: [
      "585–1,268 sq ft depending on room type (Palmero Suite at 1,500 sq ft)",
      "Open wood-beamed ceilings",
      "Gas fireplace in every room",
      "Oversized soaking tub",
      "Private garden patio or fairway views",
      "Spa rooms: private outdoor whirlpool spa on patio",
      "Courtyard Suites: private outdoor whirlpool spa in courtyard",
      "300-thread count Egyptian cotton sheets",
      "The Spa Collection bath amenities",
      "Two microfibre robes and slippers",
      "24-hour healthful room service menu",
      "Turndown service",
    ],
    uniqueDetails: [
      "Only 24 rooms — the most intimate accommodation at Pebble Beach Resorts®",
      "Full exclusive buyout available — entire property reserved by one group",
      "Situated on the 1st and 2nd fairways of Pebble Beach Golf Links®",
      "Personal concierge included — the highest staff-to-guest ratio at Pebble Beach Resorts®",
      "Adjacent to The Spa at Pebble Beach™ (Forbes Five-Star)",
      "Ideal for incentive trips, high-net-worth buddy trips, and executive corporate retreats",
    ],
    diningNames: [
      { name: "Casa Palmero Bar & Lounge", detail: "Evening wine flights and cocktails in the estate's main house — for guests only" },
      { name: "In-room dining", detail: "24-hour healthful room service menu" },
      { name: "Access to all Lodge dining", detail: "Stillwater Bar & Grill, Tap Room, Club XIX — a 5-minute walk" },
    ],
    onSiteGolf: "Pebble Beach Golf Links®",
    airportDistance: "~15 min from MRY (Monterey Regional Airport)",
    driveTimeToCourses: [
      { course: "Pebble Beach Golf Links®", minutes: 0 },
      { course: "Spyglass Hill® Golf Course", minutes: 5 },
      { course: "Del Monte™ Golf Course", minutes: 10 },
      { course: "Poppy Hills Golf Course", minutes: 8 },
      { course: "Bayonet", minutes: 20 },
      { course: "Black Horse", minutes: 20 },
    ],
    positioning: "The most exclusive accommodation at Pebble Beach Resorts® and arguably in golf. Best for high-net-worth buddy trips of up to 12–24 players who want complete privacy, a personal concierge, and the closest possible proximity to Pebble Beach Golf Links®. Corporate groups who want the entire estate for an executive retreat or incentive trip can book it exclusively.",
    faqs: [
      {
        q: "Can we rent all of Casa Palmero exclusively for our group?",
        a: "Yes — Casa Palmero™ can be reserved exclusively by a single group in advance. All 24 rooms, the main house living room, library, billiard room, bar and lounge, and heated pool become yours alone. It's the most private golf group experience available at Pebble Beach Resorts®. Get a custom quote and we'll confirm availability and coordinate the exclusive booking.",
      },
      {
        q: "How does Casa Palmero differ from The Lodge?",
        a: "The Lodge has hundreds of rooms across multiple buildings, a large spa, and 10 meeting rooms — it operates as a full resort hotel. Casa Palmero has 24 rooms in a single Mediterranean-style estate with one personal concierge for all guests. Fresh flowers daily, complimentary evening cocktails, morning yoga in the courtyard — it's a private club experience on the Pebble Beach Golf Links® fairway.",
      },
      {
        q: "Do Casa Palmero guests have access to the Pebble Beach Golf Links®?",
        a: "Yes — all Pebble Beach Resorts® golf courses are available to Casa Palmero guests, with tee times bookable up to 12 months in advance. The Spa at Pebble Beach™ is immediately adjacent. The Lodge dining, Beach & Tennis Club, and all resort amenities are accessible via courtesy shuttle.",
      },
      {
        q: "Is Casa Palmero suitable for a small corporate retreat?",
        a: "Yes — the Boardroom accommodates up to 30 guests, with a smaller conference room for up to 16 and an outdoor patio for up to 48. For executive groups of 10–24 wanting a combination of serious golf and private meeting space on the Pebble Beach Golf Links® fairway, there's nothing comparable.",
      },
      {
        q: "What is the minimum stay for a Pebble Beach round from Casa Palmero?",
        a: "A minimum stay is required to play Pebble Beach Golf Links®. Get a custom quote and we'll confirm the current requirements for your dates through our IAGTO partnership.",
      },
    ],
  },
};
